packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@namesmt/vue-query-nuxt'
  - aws-sdk
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
